<nav class="sidebar" style="position: fixed;top: 80px;left: 0;width: 250px;height: calc(100vh - 80px);background-color: rgb(206, 224, 238);box-shadow: 2px 0 10px rgba(0,0,0,0.1);overflow-y: auto;z-index: 50;">  
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <ul class="nav-menu" style=" list-style: none;">
            <?php if ($role === 'admin'): ?>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Dashboard</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Staff Management</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">User Management</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Patient Management</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Resource Management</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Financial Management</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Communication</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Analytics & Report</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">System Setting</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Audit Logs</a></li
             <?php if ($role === 'admin'): ?>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Dashboard</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Schedule</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Patients</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Appointment</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Prescription</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Lab Result</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Electronic Health Record</a></li>
            <?  php elseif ($role === 'nurse'): ?>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Dashboard</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Patients</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Medications</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Vital Signs</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Shift Reports</a></li>
             <?  php elseif ($role === 'receptionist'): ?>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Dashboard</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#') ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Patient Registration</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Appointment Booking</a></li>
                <li class="nav-item" style="margin-bottom: 0.5rem;"><a href="<?= base_url('#) ?>" class="nav-link" style="display:flex;align-items:center;padding: 1rem 2rem;color:#010101;text-decoration:none;transition: all 0.3s;border-left:3px solid transparent;">Insurance Verification</a></li>
        </ul>
    </div>
</nav> 