<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run()
    {
        $patients = [
            [
                'patient_id' => 'P2025001',
                'first_name' => 'Maria',
                'middle_name' => 'Santos',
                'last_name' => 'Cruz',
                'date_of_birth' => '1990-03-15',
                'age' => 34,
                'gender' => 'Female',
                'civil_status' => 'Married',
                'phone' => '+639171234567',
                'email' => 'maria.cruz@email.com',
                'address' => '123 Rizal Street, Barangay San Jose',
                'province' => 'Metro Manila',
                'city' => 'Quezon City',
                'barangay' => 'San Jose',
                'zip_code' => '1100',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH123456789',
                'emergency_contact_name' => 'Juan Cruz',
                'emergency_contact_phone' => '+639181234567',
                'emergency_contact_relationship' => 'Spouse',
                'medical_notes' => 'Allergic to penicillin',
                'allergies' => 'Penicillin, Shellfish',
                'blood_type' => 'O+',
                'status' => 'Active',
                'patient_type' => 'Outpatient',
                'registration_date' => date('Y-m-d', strtotime('-2 days')),
                'last_visit' => date('Y-m-d', strtotime('-1 day')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-1 day'))
            ],
            [
                'patient_id' => 'P2025002',
                'first_name' => 'Jose',
                'middle_name' => 'Dela',
                'last_name' => 'Reyes',
                'date_of_birth' => '1985-07-22',
                'age' => 39,
                'gender' => 'Male',
                'civil_status' => 'Single',
                'phone' => '+639191234568',
                'email' => 'jose.reyes@email.com',
                'address' => '456 Bonifacio Avenue, Barangay Poblacion',
                'province' => 'Rizal',
                'city' => 'Antipolo',
                'barangay' => 'Poblacion',
                'zip_code' => '1870',
                'insurance_provider' => 'Maxicare',
                'insurance_number' => 'MC987654321',
                'emergency_contact_name' => 'Ana Reyes',
                'emergency_contact_phone' => '+639201234568',
                'emergency_contact_relationship' => 'Sister',
                'medical_notes' => 'Hypertensive, taking maintenance medication',
                'allergies' => 'None known',
                'blood_type' => 'A+',
                'status' => 'Active',
                'patient_type' => 'Inpatient',
                'registration_date' => date('Y-m-d', strtotime('-5 days')),
                'last_visit' => date('Y-m-d'),
                'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'patient_id' => 'P2025003',
                'first_name' => 'Ana',
                'middle_name' => 'Garcia',
                'last_name' => 'Lopez',
                'date_of_birth' => '1995-11-08',
                'age' => 29,
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '+639211234569',
                'email' => 'ana.lopez@email.com',
                'address' => '789 Mabini Street, Barangay Centro',
                'province' => 'Laguna',
                'city' => 'Los Baños',
                'barangay' => 'Centro',
                'zip_code' => '4030',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH234567890',
                'emergency_contact_name' => 'Roberto Lopez',
                'emergency_contact_phone' => '+639221234569',
                'emergency_contact_relationship' => 'Father',
                'medical_notes' => 'Pregnant - 2nd trimester',
                'allergies' => 'Latex',
                'blood_type' => 'B+',
                'status' => 'Active',
                'patient_type' => 'Outpatient',
                'registration_date' => date('Y-m-d', strtotime('-1 week')),
                'last_visit' => date('Y-m-d', strtotime('-3 days')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 week')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-3 days'))
            ],
            [
                'patient_id' => 'P2025004',
                'first_name' => 'Roberto',
                'middle_name' => 'Mendoza',
                'last_name' => 'Silva',
                'date_of_birth' => '1978-12-03',
                'age' => 46,
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '+639231234570',
                'email' => 'roberto.silva@email.com',
                'address' => '321 Luna Street, Barangay Bagong Silang',
                'province' => 'Cavite',
                'city' => 'Bacoor',
                'barangay' => 'Bagong Silang',
                'zip_code' => '4102',
                'insurance_provider' => 'Intellicare',
                'insurance_number' => 'IC345678901',
                'emergency_contact_name' => 'Carmen Silva',
                'emergency_contact_phone' => '+639241234570',
                'emergency_contact_relationship' => 'Wife',
                'medical_notes' => 'Diabetic Type 2, regular check-ups needed',
                'allergies' => 'Aspirin',
                'blood_type' => 'AB+',
                'status' => 'Active',
                'patient_type' => 'Outpatient',
                'registration_date' => date('Y-m-d', strtotime('-10 days')),
                'last_visit' => date('Y-m-d', strtotime('-2 days')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-2 days'))
            ],
            [
                'patient_id' => 'P2025005',
                'first_name' => 'Elena',
                'middle_name' => 'Ramos',
                'last_name' => 'Torres',
                'date_of_birth' => '2010-05-20',
                'age' => 14,
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '+639251234571',
                'email' => null,
                'address' => '654 Aguinaldo Highway, Barangay Salawag',
                'province' => 'Cavite',
                'city' => 'Dasmariñas',
                'barangay' => 'Salawag',
                'zip_code' => '4114',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH456789012',
                'emergency_contact_name' => 'Miguel Torres',
                'emergency_contact_phone' => '+639261234571',
                'emergency_contact_relationship' => 'Father',
                'medical_notes' => 'Minor patient, requires guardian consent',
                'allergies' => 'Peanuts',
                'blood_type' => 'O-',
                'status' => 'Active',
                'patient_type' => 'Emergency',
                'registration_date' => date('Y-m-d'),
                'last_visit' => date('Y-m-d'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'patient_id' => 'P2025006',
                'first_name' => 'Carlos',
                'middle_name' => 'Villanueva',
                'last_name' => 'Morales',
                'date_of_birth' => '1965-09-14',
                'age' => 59,
                'gender' => 'Male',
                'civil_status' => 'Widowed',
                'phone' => '+639271234572',
                'email' => 'carlos.morales@email.com',
                'address' => '987 Katipunan Avenue, Barangay Holy Spirit',
                'province' => 'Metro Manila',
                'city' => 'Quezon City',
                'barangay' => 'Holy Spirit',
                'zip_code' => '1127',
                'insurance_provider' => null,
                'insurance_number' => null,
                'emergency_contact_name' => 'Patricia Morales',
                'emergency_contact_phone' => '+639281234572',
                'emergency_contact_relationship' => 'Daughter',
                'medical_notes' => 'Senior citizen, multiple comorbidities',
                'allergies' => 'Sulfa drugs',
                'blood_type' => 'A-',
                'status' => 'Active',
                'patient_type' => 'Inpatient',
                'registration_date' => date('Y-m-d', strtotime('-3 weeks')),
                'last_visit' => date('Y-m-d', strtotime('-1 week')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 weeks')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-1 week'))
            ],
            [
                'patient_id' => 'P2025007',
                'first_name' => 'Isabella',
                'middle_name' => 'Fernandez',
                'last_name' => 'Gonzales',
                'date_of_birth' => '1992-01-28',
                'age' => 32,
                'gender' => 'Female',
                'civil_status' => 'Married',
                'phone' => '+639291234573',
                'email' => 'isabella.gonzales@email.com',
                'address' => '147 EDSA Extension, Barangay Pasong Tamo',
                'province' => 'Metro Manila',
                'city' => 'Makati',
                'barangay' => 'Pasong Tamo',
                'zip_code' => '1231',
                'insurance_provider' => 'Medicard',
                'insurance_number' => 'MD567890123',
                'emergency_contact_name' => 'Diego Gonzales',
                'emergency_contact_phone' => '+639301234573',
                'emergency_contact_relationship' => 'Husband',
                'medical_notes' => 'Post-operative follow-up',
                'allergies' => 'Iodine',
                'blood_type' => 'B-',
                'status' => 'Active',
                'patient_type' => 'Outpatient',
                'registration_date' => date('Y-m-d', strtotime('-1 month')),
                'last_visit' => date('Y-m-d', strtotime('-5 days')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 month')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-5 days'))
            ],
            [
                'patient_id' => 'P2025008',
                'first_name' => 'Miguel',
                'middle_name' => 'Castro',
                'last_name' => 'Hernandez',
                'date_of_birth' => '2005-04-12',
                'age' => 19,
                'gender' => 'Male',
                'civil_status' => 'Single',
                'phone' => '+639311234574',
                'email' => 'miguel.hernandez@email.com',
                'address' => '258 Commonwealth Avenue, Barangay Batasan Hills',
                'province' => 'Metro Manila',
                'city' => 'Quezon City',
                'barangay' => 'Batasan Hills',
                'zip_code' => '1126',
                'insurance_provider' => 'PhilHealth',
                'insurance_number' => 'PH678901234',
                'emergency_contact_name' => 'Rosa Hernandez',
                'emergency_contact_phone' => '+639321234574',
                'emergency_contact_relationship' => 'Mother',
                'medical_notes' => 'Sports injury - knee rehabilitation',
                'allergies' => 'None known',
                'blood_type' => 'O+',
                'status' => 'Active',
                'patient_type' => 'Outpatient',
                'registration_date' => date('Y-m-d', strtotime('-2 weeks')),
                'last_visit' => date('Y-m-d', strtotime('-4 days')),
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 weeks')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-4 days'))
            ]
        ];

        // Clear existing test data first
        $this->db->table('patients')->where('patient_id LIKE', 'P2025%')->delete();

        // Insert new patient data
        foreach ($patients as $patient) {
            $this->db->table('patients')->insert($patient);
        }

        echo "Patient seeder completed successfully!\n";
        echo "Created " . count($patients) . " test patients:\n";
        
        foreach ($patients as $patient) {
            echo "- {$patient['patient_id']}: {$patient['first_name']} {$patient['last_name']} ({$patient['patient_type']})\n";
        }
        
        echo "\nPatient statistics:\n";
        echo "- Active patients: " . count(array_filter($patients, fn($p) => $p['status'] === 'Active')) . "\n";
        echo "- Outpatients: " . count(array_filter($patients, fn($p) => $p['patient_type'] === 'Outpatient')) . "\n";
        echo "- Inpatients: " . count(array_filter($patients, fn($p) => $p['patient_type'] === 'Inpatient')) . "\n";
        echo "- Emergency patients: " . count(array_filter($patients, fn($p) => $p['patient_type'] === 'Emergency')) . "\n";
        echo "- Insured patients: " . count(array_filter($patients, fn($p) => !empty($p['insurance_provider']))) . "\n";
        echo "- Uninsured patients: " . count(array_filter($patients, fn($p) => empty($p['insurance_provider']))) . "\n";
    }
}
